### ISSUE TITLE
[EXPERIMENTAL CHANGE] Change the `descpription` of an `Endpoint<H: Handler>` to "shortname" of `Handler`

### ISSUE THREAD

**Issue by lschlesinger** [Apodini/Apodini#114]
**Is your change related to a problem? Please describe.**
Currently, the `description` of an `Endpoint<H: Handler>` is set to [`String(describing: Handler)`](https://github.com/Apodini/Apodini/blob/develop/Sources/Apodini/Semantic%20Model%20Builder/Model/Endpoint.swift#L89)
To my understanding, as of now, the description is mainly used to print error messages. In case of more complex `Handler`s, (e.g., including several parameters... such as the `TraditionalGreeter` in the current main.swift), this can lead to unreadable error messages.
If one would try to add a `TraditionalGreeter` more than once with the same `operation` and at the same path, this would lead to an error message, that is hard to read:
![image](https://user-images.githubusercontent.com/41366522/104092982-bc691d00-5287-11eb-925a-547e41d1e249.png)

**Propose a solution**
I suggest to reduce the respective `description` to the name of the `Handler`, e.g. in the `TraditionalGreeter` in the given example.
This would lead to clean, readable outputs such as:
![image](https://user-images.githubusercontent.com/41366522/104093015-06ea9980-5288-11eb-847f-d4377c902a05.png)

Furthermore, I could think of other use cases where the `Handler`'s name can be harnessed. For example, the description of an `OpenAPI.Operation` (i.e. and endpoint, that is defined by a unique path and HTTP operation):
<img src="https://user-images.githubusercontent.com/41366522/104093147-e838d280-5288-11eb-8685-eece01fbe827.png" width="400" >

**QUESTION: Is  the endpoint's description, I want to refactor, used anywhere else except for error descriptions and tests or planned to be used for anything in this certain form in the future that would disallow for the proposed change?**

If not, refactoring would be an easy job ;)

**Comment by bauer-andreas** [comment]
Maybe we can use `CustomDebugStringConvertible` and its `debugDescription` property to return that detailed description.
