### ISSUE TITLE
Upgrade OAS to correctly represent RESTful API with HATEOAS

### ISSUE THREAD

**Issue by lschlesinger** [Apodini/Apodini#118]
It's more a shortcoming than a bug, as the described current behavior of the OpenAPIExporter was planned to be adapted iteratively to represent a RESTful application correctly. 

**Bug/problem description**
Currently, the `responses` section in the OpenAPI Specification does not correctly represent the response returned by a RESTful API. 
As an initial version, this section provides documentation for the return type of the `Handler`s `handle()` function.
Having a RESTful API always returning an object including a nested `data` object as well as a `_links` object, this section needs to be refactored. 

**To Reproduce**
Following examples base on the following example `TestWebService`

```swift
struct TestWebService: Apodini.WebService {

... // `Handler`s and other types

    @PathParameter var userId: Int

    var content: some Component {
        Group("swift") {
            Text("Hello Swift! 💻")
                .response(EmojiMediator())
            Group("5", "3") {
                Text("Hello Swift 5! 💻")
            }
        }
         Group("user", $userId) {
            UserHandler(userId: $userId)
        }
    }
}
```

#### Current behavior
Definition of **`handle()` function** in `Text.swift` returning a **String**:
```swift 
public func handle() -> String {
    text
}
```

A request to http://localhost:8080/v1/swift object would lead to the following **JSON** **response**:

```
{
    "data": "✅ Hello Swift! 💻 ✅",
    "_links": {
        "5_3": "http://127.0.0.1:8080/v1/swift/5/3",
        "self": "http://127.0.0.1:8080/v1/swift" 
    }
}
```
Whereas the current **OpenAPI Specification**  lists the response as a simple **String** that is returned:

``` 
"responses": {
    "200": {
        "content": {
            "text/plain": {
                "schema": {
                    "type": "string"
                }
            }
        }
    }
}
```
#### Possibly expected OAS

```
"responses": {
    "200": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "string"
                        },
                        "_links": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string",
                                "format": "url"
                            }
                        }
                    }
                }
            }
        }
    }
    ...
}
```

#### Current behavior
Definition of **`UserHandler`** with respective **`handle()`**  function returning a **`User`** object:
```swift 
struct User: Codable {
    var id: Int
}

struct UserHandler: Handler {
    @Parameter var userId: Int

    func handle() -> User {
        User(id: userId)
    }
}
```
A request to http://localhost:8080/v1/user/1 object would lead to the following **JSON** **response**  object including the `data` and `_links` to further explore the API:
```
{
    "data": {
        "id": 1
    },
    "_links": {
        "self": "http://127.0.0.1:8080/v1/user/:B285FABD-CA5A-4432-A456-8050864E4E05"
    }
}
```
Whereas the current **OpenAPI Specification** lists the response as a **`User`**  object that is returned:
```
"responses": {
    "200": {
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/User"
                }
            }
        }
    }
}
```

#### Possibly expected OpenAPI Specification
```
"responses": {
    "200": {
        "content": {
            "application/json": {
                "schema": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "$ref": "#/components/schemas/User"
                        },
                        "_links": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string",
                            }
                        }
                    }
                }
            }
        }
    }
}
```
The described, expected `responses` section of the OpenAPI Specification would lead, when pasted as a part of a complete OpenAPI Specification into https://editor.swagger.io/, to an example return value of:
```
{
    "data": {
        "id": 0
    },
    "_links": {
        "additionalProp1": "string",
        "additionalProp2": "string",
        "additionalProp3": "string"
    }
}
``` 
which matches the actual return described above with the modification that `_links` is defined as always including `self` but can have `additionalProperties` (automatically named "additionalProp1" etc.) providing further links. This assumes, that the OpenAPI Specification does not have to document the exact amount of further links. It's a valid assumption, as this information is created by the RESTExporter during runtime.

### Summary
With regard to the different return types of the `Handler`s `handle()` function in the two examples, in theOpenAPI Specification only the property `data` differs, whereas `_links` is exactly the same as the type of this object is not endpoint specific (except for how many other links (beside `_self`) are included, which is not known in advance and captured by the "OpenAPI Specification feature" `additionalProperties` which mimics a placeholder for an arbitrarily repeated property, i.e. a dictionary of arbitrary size).

**Comment by PSchmiedmayer** [comment]
I think this is an important point, thanks for the issue!

In general I could imagine two different approaches.
1. The REST exporter share an intermediate step in creating a RESTful API model that can be registered to the router and the OpenAPI  Interface Exporter so there is no real duplication between the logic of constructing the responses if there are variations. If it is always just `data` and `_links` it would even be a feasible approach to not really share any logic. Even if we want to follow the approach listed under (2) later it would be great to make this configurable to adding a pure JSON API later on would be easier. 
2. The OpenAPI interface exporter actually also registers routes that do not reflect a RESTful API but a very simple and basic JSON based API as currently described with the OpenAPI specification. This would be closer to the initial idea of RESTful APIs as described by Fielding that are discoverable using links and don't inherently need an Interface Specification Language (IDL). On the other hand most modern APIs don't really differentiate between JSON based APIs documented by an OpenAPI specification and RESTful APIs that are discoverable using links. Introducing an other JSON based API is then separately reachable to the REST API. If. we follow this approach we should also make it somehow configurable to we could follow the approach of (1) later if this would be desirable.

It would be interesting to know your input and opinion! We can also discuss this in the meeting tomorrow or during the work meeting.

Apart from the feedback to the content:
It seems like the second example has a wrong link in the description (http://localhost:8080/v1/swift)[http://localhost:8080/v1/swift]. It might be good to replace the URLs with Swift code of the corresponding `Handler`s and return types. Maybe grouping the `Handler`, type, response, and specification of each example next to each other would make it easier to understand the example 👍

**Comment by lschlesinger** [comment]
Thanks for that useful explanation and input! I've restructured the examples and hope this makes it clearer :) Besides, I would vote for your suggestion (1): 
It seems this uses more of the existing infrastructure, avoids duplication of concepts (e.g., endpoints that serve almost the same content, except for hyperlinks) and could therefore potentially be more maintainable in the long run. Otherwise we would have to maintain another (slightly different) JSONAPI exporter.

In this case, I will collaborate with @Supereg to share the same representation of responses.
