### ISSUE TITLE
[INTERNAL CHANGE] Explicitly handle `@Parameter` declarations in Guards and ResponseTransformers.

### ISSUE THREAD

**Issue by bauer-andreas** [Apodini/Apodini#220]
**Is your change related to a problem? Please describe.**
At the moment the `SemanticModelBuilder` only considers `@Parameter` declarations in the `Handler` for a given `Endpoint`. Though `@Parameter`s are also allowed and indeed injected on guards and response transformers.
Meaning it is the responsibility to declare matching `@Parameter`s on guards and ResponseTransformers
(while it is possible, it is kind a huzzle to declare matching parameters, as it is rather tricky to have the same Parameter with the same `UUID`).
They can't declare new Parameters (as they won't surface in the `Endpoint` model).

**Propose a solution**
Apodini should consider parsing `@Parameter`s on Guards and ResponseTransformers as well (meaning adding those Parameters to the `Endpoint` model),
ideally supporting a nicer way to declare the **same** parameters on guards and ResponseTransformers.

**Comment by theMomax** [comment]
Fixed by #286
