### ISSUE TITLE
[MAJOR FEATURE OpenAPIExporter] Add security scheme object to OAS

### ISSUE THREAD

**Issue by lschlesinger** [Apodini/Apodini#233]
**Describe your use case**
In case the REST API implements security mechanisms, the OpenAPIExporter should properly document the applied security schema(s) for every endpoint.

**Current state**
As Apodini DSL does not yet support the definition of authentication and other security mechanisms. The generated OAS does not contain a field `security`, neither on document (whole API) nor on operation (endpoint) level. 

**Propose an approach**
Simultaneously to integrating authentication and security mechanisms to the exported REST API, the OpenAPIExporter should map such concepts provided in the Apodini DSL to swift types that can be translated in OAS. Such swift types are already implemented in the [OpenAPIKit](https://github.com/mattpolzin/OpenAPIKit/) library: `OpenAPI.SecurityScheme`, `OpenAPI.OauthFlow`, `OpenAPI.Docuement.SecurityRequirement`, as shown [here](https://github.com/mattpolzin/OpenAPIKit/blob/master/documentation/specification_coverage.md#security-scheme-object-openapisecurityscheme).

**Additional context**
Some information retrieved from the [official documentation](https://swagger.io/specification/):
According to the documentation the `security` field in an OpenAPI document represents a "_declaration of which security mechanisms can be used across the API_", as array of [**Security Requirement Objects**](https://swagger.io/specification/#security-requirement-object). In other words, it is a summary of all security mechanisms used on [**Operation Object**](https://swagger.io/specification/#operation-object)s throughout the API.
A security requirement object lists required security schemas to execute this operation, encapsulated in **[Security Scheme Object](https://swagger.io/specification/#security-scheme-object)**. Supported schemes are HTTP authentication, an API key (either as a header, a cookie parameter or as a query parameter), OAuth2's common flows (implicit, password, client credentials and authorization code) as defined in RFC6749, and OpenID Connect Discovery.

**Comment by bauer-andreas** [comment]
Solved by #340. As described in the PR, due to different modelling strategies of security requirements between OpenAPI and ApodiniAuthorization the mapping is not perfect.
