### ISSUE TITLE
[BUG] Swagger UI is not able to send requests to web service

### ISSUE THREAD

**Issue by AndiBraimllari** [Apodini/Apodini#271]
**Describe the bug**
Simply downloading and running the Apodini Template shows an error when accessing the Swagger-UI. When accessed through Chrome the following message is shown ```Failed to fetch. Possible Reasons: CORS Network Failure URL scheme must be "http" or "https" for CORS request.```. When ran in Safari another bug was thrown. On the other hand, using cURL worked fine with the endpoints.

**To Reproduce**
Download the Apodini Template and run it, then open Chrome and go to the Swagger-UI page and execute an endpoint.

**Expected behavior**
Executing endpoints of the Apodini Template from the Swagger-UI work without bugs.

**Environment (enter your versions)**

 - Swift Version: Apple Swift version 5.3.2
 - Xcode Version: Version 12.4 (12D4e)

**Additional context**
Recently started using Big Sur 11.2.3.

**Comment by ridvan-cln** [comment]
Hi @AndiBraimllari @PSchmiedmayer,

I think this is a typical CORS issue that I have seen in many projects already.
I "solved" the issue by just adding `app.middleware.use(CORSMiddleware(configuration: .default()))` , before we start the vapor server in `Application+Vapor`.

I see two main possibilities to solve this issue:

- We add the CORS middleware by default to the swagger-ui requests only and close this issue for now
- We give developers a configuration to setup middlewares as they want (could be tricky to do this in an agnostic way, if we want to move from vapor), I think we don't have this option yet right?

What do you guys think?

**Comment by ridvan-cln** [comment]
Hey guys,
little update from me on this topic. I have read a few articles on how to securely configure CORS and it is a very complex topic tbh. (https://www.pivotpointsecurity.com/blog/cross-origin-resource-sharing-security/)

But what I found out is that one can simply avoid this issue by opening Swagger UI from the URL http://127.0.0.1:8080/oas-ui instead of http://localhost:8080/oas-ui . (see screenshots below)
The reason is that for some reason 127.0.0.1 and localhost are not seen as the same Origin and CORS forbids that.

Do you think we can close this issue now? @PSchmiedmayer @AndiBraimllari 
![Bildschirmfoto 2021-09-20 um 17 41 20](https://user-images.githubusercontent.com/1402089/134031616-cd2f21da-a15c-4f48-84a5-a5307eb49807.png)
![Bildschirmfoto 2021-09-20 um 17 41 40](https://user-images.githubusercontent.com/1402089/134031638-64ae6f0c-c0f0-4e4a-973b-2fead5dfdacf.png)

**Comment by AndiBraimllari** [comment]
Hello,
I'm no longer actively working with this project, please feel free to proceed as you best see fit.

**Comment by PSchmiedmayer** [comment]
@ridvan-cln Thanks for the input, nice catch!

I would suggest the following two things
1. We somehow need a way in a web service to configure it's outside domain name or IP address. If there is no one provided we should just use "localhost" as it is independent of an IPv4 or IPv6 setup. This should be configurable outside the OpenAPI spec and should replace `OpenAPI.ExporterConfiguration`'s `serverUrls`. This would allow is to define how the web service is exposed and this can then even be configurable using Swift argument parser arguments. This information might even be useful for other exporters, e.g. the links section in the REST exporter which is currently also just using 127.0.0.1.
2. The second step would be to make sure that all requests to the web service's OpenAPI document are forwarded to the domain name/IP address configured in the web service. This then makes sure the CORS is no longer an issue as the server url in the OpenAPI document and the visited website are guaranteed to be the same. 

What to you think about that solution @ridvan-cln ?

**Comment by ridvan-cln** [comment]
Hi @PSchmiedmayer,

yes this sounds like a good approach.

But as I understood now, just by defining the serverUrl as Swift argument won't ensure that the webService is actually deployed there right? We will just use this information internally for Exporters that need it (e.g. OpenAPI).

I will start with this approach then 👍

**Comment by PSchmiedmayer** [comment]
@ridvan-cln Yes, defining it as an argument (that is then passed to a `Configuration`) doesn't guarantee that it is actually deployed there. But it would enable a developer to provide a default value of "localhost" for development purposes. When starting the web service, you can then pass an actual domain name to the web service using its command-line arguments and this domain name that is then used when running the web service in the production environment, ensuring that the relevant exporters are aware of this information. 

Thanks a lot for taking a look at the issue 💪

**Comment by ridvan-cln** [comment]
Hi @PSchmiedmayer,

I created a Pull Request for this Issue now. It seems like we already had a configuration for this "HTTPConfiguration", if I understood correctly, but we didn't make use of it anywhere.
As this is my first code change please be extra careful 🤣 

Have a nice weekend!
