### ISSUE TITLE
Protobuffer generation: handle many Parameters

### ISSUE THREAD

**Issue by nityanandaz** [Apodini/Apodini#62]
**Is your feature request related to a problem? Please describe.**
Methods of a gRPC service only accept one message argument:

```proto
service GreeterService {
  rpc handle (StringMessage) returns (StringMessage);
}
```

This is invalid:

```proto
service GreeterService {
  rpc handle (StringMessage, BoolMessage) returns (StringMessage);
}
```

However, we might want to declare many `Apodini.Paramter`s in a `Apodini.Component`:

```swift
struct Greeter: Handler {
    @Parameter
    var name: String
    
    @Parameter
    var isFormal: Bool
    
    func handle() -> String {...}
}
```

**Propose a solution**

_Alternative 1_: Interpret the Component itself as the top-level message type. 🥇

_Alternative 2_: Pre-generate _tuple messages_, but with named fields. Possibly with **gyb**.

_Alternative 3_: A top-level message with one repeated field of a _union type_ message using **oneof**.

**Additional context**
- https://github.com/Apodini/Apodini/pull/33#discussion_r541013183
- https://developers.google.com/protocol-buffers/docs/proto3#oneof
- https://en.wikipedia.org/wiki/Union_type
- https://en.wikipedia.org/wiki/Tagged_union

**Comment by nityanandaz** [comment]
The field name is not so relevant, but the unique number must match.

Ref.: ...

**Comment by PSchmiedmayer** [comment]
@nityanandaz I completely missed this issue when it was created. I like the _Alternative 1_ as proposed in the issue above 👍
All `@Parameter`s would then be fields of this type?
I would not try to work with code generation as described in Alternative 2. Either just using the `Handler` as a top level message or creating a new message type that has the exact same fields as marked with `@Parameter` sounds reasonable to me.

**Comment by nityanandaz** [comment]
Thanks @PSchmiedmayer. @moritzschuell and I just revived the issue. The `Greeter` handler should become:

```
message GreeterMessage {
    string name = 1;
    bool isFormal = 2;
}
```

**Comment by PSchmiedmayer** [comment]
@nityanandaz @moritzschuell Looks good to me 🚀

**Comment by moritzschuell** [comment]
@nityanandaz fyi; maybe we can move this functionality to the shared logic in `Endpoint+GRPC.swift`: 

- This is the code that currently is used by the gRPC exporter to generate the default field-tags / field-numbers: https://github.com/Apodini/Apodini/blob/a58804042004a5bbff2cbdd907ea315be7aa260c/Sources/Apodini/Semantic%20Model%20Builder/gRPC/GRPCInterfaceExporter.swift#L28-L34

- Explicitly defined field-numbers "override" the default numbers:
https://github.com/Apodini/Apodini/blob/a58804042004a5bbff2cbdd907ea315be7aa260c/Sources/Apodini/Semantic%20Model%20Builder/gRPC/GRPCInterfaceExporter.swift#L105-L110
