### ISSUE TITLE
[BUG] EventLoopFuture should be Encodable

### ISSUE THREAD

**Issue by tgymnich** [Apodini/Apodini#72]
**Describe the bug**

By replacing `ResponseEncodable` with `Encodable`, we lost Vapor's `EventLoopFuture: ResponseEncodable` extension, meaning our handle() functions can't return `EventLoopFutures` anymore.

**Relevant test case:** `CustomComponentTest.swift`

The invalid return type caused the test component's Response type to default to Never, which we didn't catch because this specific test case directly invokes handle() instead of going via the witness table.

**Expected behavior**

- `EventLoopFuture conforms to `Encodable`
- Unit Tests should test for this

**Comment by tgymnich** [comment]
cc @lukaskollmer @PSchmiedmayer @Supereg

**Comment by bauer-andreas** [comment]
Shouldn’t we just be able to make a extension to Encodable (and maybe decodable for consistency?), adding an encode method returning an event loop and then just add the extension to EventLoopFuture, just how it is done for ResponseEncodable? Or am I missing something in this quick thought?

**Comment by tgymnich** [comment]
@Supereg well its not that simple they have like 5 more layers underneath. e.g.: `ContentContainer` and `ContentEncoder`, ...

Also there is nothing returned when encoding encodables. Encodables are encoded into the Encoder passed as a function Argument.

**Comment by bauer-andreas** [comment]
> Also there is nothing returned when encoding encodables. Encodables are encoded into the Encoder passed as a function Argument.

Then return type of EventLoopFutute<Void> should work? I mean we have full control, as we are the ones calling such a method.

but yeah, I probably underestimate the work needed for EventLoopFuture to conform to Encodable.

I will need to give that a more detailed look to properly estimate the changes needed thought.

**Comment by tgymnich** [comment]
@Supereg after some more thoughts, I think extending Encodable and returning an EventLoopFuture is defiantly the right idea.

So creating another function that returns an EventLoopFuture and using that in encode(_:) won't work. But using this function instead of encode might work

**Comment by bauer-andreas** [comment]
I think this can be closed as of #98?
