### ISSUE TITLE
[BUG] Protobuffer generation: handle `Apodini.PathParameter`

### ISSUE THREAD

**Issue by nityanandaz** [Apodini/Apodini#96]
**Describe the bug**
`TestWebSevice` produces an invalid `.proto` declaration:
```proto
syntax = "proto3";

service V1User:E1A4F8A7-9E95-4Ea3-Ae9F-50Cb99B19792Service {
  rpc handle (IntMessage) returns (UserMessage);
}
```

**To Reproduce**
1. Run target `TestWebService`
2. Open link http://0.0.0.0:8080/apodini/proto

**Expected behavior**
🤷 TBD

**Additional context**
- https://github.com/Apodini/Apodini/blob/bf59a8d120936c1735b2e580baeb4b62ca822604/Sources/TestWebService/main.swift#L98

**Comment by bauer-andreas** [comment]
Some context:
I'm currently in the process of creating a dedicated path model in the shared semantic model builder to more easily parse PathComponents and PathParameters. Currently the raw `Parameter` instance is supplied to the `PathComponent` array, which is not really great to handle.
A standalone `@PathParameter` instance (or a `@Parameter` instance derived from a `@PathParameter`) doesn't yield any useful information. In fact, the only info we have is the `id`. As a `@PathParameter` can be defined in multiple `Handlers` we even don't have a distinct name/label for it.
So we really only have proper information for a `@PathParameter` in the context of a specific `Endpoint`/`Handler`. As this is given, it isn't really a problem. I just means that with the current approach it is rather ugly to handle path parameters.

As I need a proper PathParameter model as well when working on the implementation of the Relationship retrieval, first step will be to create a dedicated PR creating such a model, which is more powerful.

With that you could then use the parameter name in the service name, but not sure if that improves your situation, as having the parameter name isn't ideal as well (as having a service name `V1useruserId` isn't semantically valuable), but would at least remove the UUID string.

**Comment by nityanandaz** [comment]
This is indeed resolved and no longer produces an invalid `.proto` file 🙂 

https://github.com/Apodini/Apodini/blob/0ac1944d5ebfc51315078fe0c70f1c985f9c785c/TestWebService/Sources/TestWebService/UserSubsystem/Components/UserComponent.swift#L12

becomes

```proto
service V1UseruseridService {
  rpc userhandler (UserHandlerMessage) returns (UserMessage);
}

message UserHandlerMessage {
  IntMessage userId = 1;
}

...
```
